export type SeedOpportunity = {
  id: string;
  company: string;
  country: string;
  flag: string;
  jurisdiction: string;
  companyType: "operator" | "vendor" | "studio" | "affiliate";
  score: number;
  fit: number;
  confidence: number;
  recommendation: "pursue" | "qualify" | "monitor";
  status: "new" | "review" | "qualified" | "contacted" | "meeting" | "watch";
  signals: string[];
  summary: string;
  whyNow: string;
  potentialNeeds: string[];
  risks: string[];
  detectedAt: string;
  website?: string;
  employees?: number;
};

export type SeedSignal = {
  id: string;
  type: string;
  company: string;
  companyId: string;
  jurisdiction: string;
  flag: string;
  title: string;
  summary: string;
  confidence: number;
  source: "primary" | "secondary" | "company" | "inference";
  sourceName: string;
  detectedAt: string;
  publishedAt?: string;
  url?: string;
};

export type SeedCompany = {
  id: string;
  name: string;
  legalName?: string;
  country: string;
  flag: string;
  type: "operator" | "vendor" | "studio" | "affiliate" | "other";
  employees?: number;
  website?: string;
  description: string;
  licenses: number;
  signals: number;
  score?: number;
  aliases: string[];
  domains: string[];
  isActive: boolean;
};

export type SeedLicense = {
  id: string;
  company: string;
  companyId: string;
  licenseNumber: string;
  jurisdiction: string;
  flag: string;
  regulator: string;
  licenseType: string;
  status: "active" | "pending" | "suspended" | "revoked" | "expired" | "conditional";
  legalEntity: string;
  effectiveDate: string;
  expiryDate?: string;
  lastChecked: string;
};

export type SeedNewsArticle = {
  id: string;
  title: string;
  publisher: string;
  publishedAt: string;
  excerpt: string;
  url: string;
  topics: string[];
  entities: string[];
  signalTypes: string[];
};

export type SeedContact = {
  id: string;
  name: string;
  title: string;
  company: string;
  companyId: string;
  email?: string;
  linkedin?: string;
  isDecisionMaker: boolean;
  confidence: number;
};

export const SEED_OPPORTUNITIES: SeedOpportunity[] = [
  {
    id: "opp-1",
    company: "BetNova Group",
    country: "Brazil",
    flag: "🇧🇷",
    jurisdiction: "Brazil (Federal)",
    companyType: "operator",
    score: 96,
    fit: 9.4,
    confidence: 92,
    recommendation: "pursue",
    status: "new",
    signals: ["NEW_LICENSE", "FUNDING", "HIRING_SURGE", "MARKET_EXPANSION"],
    summary: "BetNova received a new Brazilian federal gaming license and closed an €8M Series A. Currently hiring 5 backend engineers and 2 platform architects — no known platform provider identified.",
    whyNow: "New Brazilian regulation opening + fresh funding + active hiring with no platform lock-in",
    potentialNeeds: ["Casino platform", "Payment integration", "Game aggregation", "KYC/AML"],
    risks: ["Brazilian regulatory timeline uncertain", "May be evaluating competitors"],
    detectedAt: "2026-08-10T14:30:00Z",
    website: "betnova.com.br",
    employees: 85,
  },
  {
    id: "opp-2",
    company: "Circa Sports Arizona LLC",
    country: "United States",
    flag: "🇺🇸",
    jurisdiction: "Arizona, USA",
    companyType: "operator",
    score: 86,
    fit: 7.8,
    confidence: 78,
    recommendation: "pursue",
    status: "review",
    signals: ["NEW_LICENSE", "MARKET_EXPANSION"],
    summary: "Circa Sports received an Arizona event-wagering operator license as a tribal designee. New market entry creates need for sportsbook technology and platform infrastructure.",
    whyNow: "Just received Arizona license — greenfield market entry with infrastructure needs",
    potentialNeeds: ["Sportsbook platform", "Platform infrastructure", "Payment processing"],
    risks: ["May extend existing Nevada platform", "Tribal partnership may dictate vendor"],
    detectedAt: "2026-08-09T10:15:00Z",
    website: "circasports.com",
    employees: 450,
  },
  {
    id: "opp-3",
    company: "NovaBet",
    country: "Malta",
    flag: "🇲🇹",
    jurisdiction: "Malta (MGA)",
    companyType: "operator",
    score: 82,
    fit: 8.6,
    confidence: 70,
    recommendation: "qualify",
    status: "new",
    signals: ["PROVIDER_CHANGE", "ENGINEERING_HIRING"],
    summary: "NovaBet appears to be migrating away from their current platform provider. 4 platform engineering roles posted in the last 2 weeks suggest in-house build or new vendor evaluation.",
    whyNow: "Active provider change window — currently evaluating alternatives",
    potentialNeeds: ["Platform migration", "Engineering services", "API integration"],
    risks: ["May be building in-house", "Migration timeline unclear"],
    detectedAt: "2026-08-08T16:45:00Z",
    website: "novabet.com",
    employees: 220,
  },
  {
    id: "opp-4",
    company: "GoldStar Gaming",
    country: "Canada",
    flag: "🇨🇦",
    jurisdiction: "Ontario, Canada",
    companyType: "operator",
    score: 79,
    fit: 7.2,
    confidence: 65,
    recommendation: "qualify",
    status: "new",
    signals: ["NEW_BRAND", "MARKET_EXPANSION"],
    summary: "GoldStar Gaming announced a new casino brand targeting the Ontario iGaming market. Early-stage opportunity — launch timeline unclear but active recruitment underway.",
    whyNow: "New brand launch in regulated Ontario market — needs full tech stack",
    potentialNeeds: ["White-label platform", "Game content", "Ontario compliance"],
    risks: ["Early stage — may not launch", "Ontario market increasingly competitive"],
    detectedAt: "2026-08-07T09:20:00Z",
    website: "goldstargaming.ca",
    employees: 35,
  },
  {
    id: "opp-5",
    company: "Betway Group",
    country: "United Kingdom",
    flag: "🇬🇧",
    jurisdiction: "UK (UKGC)",
    companyType: "operator",
    score: 74,
    fit: 6.8,
    confidence: 82,
    recommendation: "monitor",
    status: "watch",
    signals: ["LICENSE_CHANGE", "REGULATORY_CHANGE"],
    summary: "Betway's UKGC license conditions were modified following a regulatory review. May indicate operational changes that create vendor evaluation windows.",
    whyNow: "License modification may trigger compliance-driven platform changes",
    potentialNeeds: ["Compliance tooling", "Responsible gambling tools", "Reporting"],
    risks: ["Large incumbent — long sales cycle", "May handle internally"],
    detectedAt: "2026-08-06T11:00:00Z",
    website: "betway.com",
    employees: 1800,
  },
  {
    id: "opp-6",
    company: "Luckia Gaming Group",
    country: "Spain",
    flag: "🇪🇸",
    jurisdiction: "Spain (DGOJ)",
    companyType: "operator",
    score: 71,
    fit: 7.5,
    confidence: 68,
    recommendation: "qualify",
    status: "new",
    signals: ["ACQUISITION", "MARKET_EXPANSION", "NEW_PRODUCT"],
    summary: "Luckia acquired a smaller LatAm-focused operator and announced expansion into Colombia and Peru. Needs to integrate acquired tech stack and scale for new markets.",
    whyNow: "Post-acquisition integration creates vendor consolidation opportunity",
    potentialNeeds: ["Platform consolidation", "LatAm payment integration", "Multi-market compliance"],
    risks: ["May retain acquired company's stack", "Decision timeline post-M&A unclear"],
    detectedAt: "2026-08-05T08:30:00Z",
    website: "luckia.es",
    employees: 600,
  },
  {
    id: "opp-7",
    company: "Pinnacle Entertainment",
    country: "Curaçao",
    flag: "🇨🇼",
    jurisdiction: "Curaçao",
    companyType: "operator",
    score: 68,
    fit: 6.5,
    confidence: 60,
    recommendation: "monitor",
    status: "watch",
    signals: ["NEW_CASINO", "TECHNOLOGY_PARTNER_SEARCH"],
    summary: "Pinnacle launched a new crypto-friendly casino brand. Job postings mention 'evaluating white-label and turnkey solutions' — possible RFP incoming.",
    whyNow: "New brand launch + explicit mention of evaluating solutions",
    potentialNeeds: ["White-label casino", "Crypto payment integration", "Game aggregation"],
    risks: ["Curaçao regulatory uncertainty", "Crypto focus may limit fit"],
    detectedAt: "2026-08-04T15:10:00Z",
    website: "pinnacle.com",
    employees: 150,
  },
  {
    id: "opp-8",
    company: "Yolo Group",
    country: "Estonia",
    flag: "🇪🇪",
    jurisdiction: "Estonia (EMTA)",
    companyType: "operator",
    score: 65,
    fit: 7.0,
    confidence: 72,
    recommendation: "monitor",
    status: "new",
    signals: ["ENGINEERING_HIRING", "DEVOPS_HIRING"],
    summary: "Yolo Group posting for senior platform engineers and DevOps leads. Pattern suggests infrastructure modernization or platform rebuild.",
    whyNow: "Active infrastructure investment — may be evaluating build vs. buy",
    potentialNeeds: ["Platform infrastructure", "Cloud migration", "DevOps tooling"],
    risks: ["Strong in-house engineering team", "May be building internally"],
    detectedAt: "2026-08-03T12:00:00Z",
    website: "yolo.com",
    employees: 900,
  },
  {
    id: "opp-9",
    company: "Wazdan Games",
    country: "Malta",
    flag: "🇲🇹",
    jurisdiction: "Malta (MGA)",
    companyType: "studio",
    score: 58,
    fit: 5.8,
    confidence: 75,
    recommendation: "monitor",
    status: "watch",
    signals: ["NEW_PRODUCT", "MARKET_EXPANSION"],
    summary: "Wazdan expanding game portfolio with live dealer vertical. Looking for integration partners in new markets.",
    whyNow: "New vertical launch — may need aggregation and distribution partners",
    potentialNeeds: ["Game aggregation", "Market access", "Certification support"],
    risks: ["Studio, not operator — different buying pattern", "May use existing aggregators"],
    detectedAt: "2026-08-02T09:45:00Z",
    website: "wazdan.com",
    employees: 300,
  },
];

export const SEED_SIGNALS: SeedSignal[] = [
  {
    id: "sig-1",
    type: "NEW_LICENSE",
    company: "BetNova Group",
    companyId: "comp-1",
    jurisdiction: "Brazil",
    flag: "🇧🇷",
    title: "BetNova receives Brazilian federal gaming license",
    summary: "BetNova Group has been granted a federal gaming license under Brazil's new iGaming regulatory framework, authorizing online casino and sports betting operations.",
    confidence: 95,
    source: "primary",
    sourceName: "SECAP (Brazil)",
    detectedAt: "2026-08-10T14:30:00Z",
    publishedAt: "2026-08-10T12:00:00Z",
  },
  {
    id: "sig-2",
    type: "FUNDING",
    company: "BetNova Group",
    companyId: "comp-1",
    jurisdiction: "Brazil",
    flag: "🇧🇷",
    title: "BetNova closes €8M Series A funding round",
    summary: "BetNova Group closed an €8M Series A led by Acme Ventures with participation from iGaming Capital Partners. Funds earmarked for technology and market expansion.",
    confidence: 92,
    source: "company",
    sourceName: "Company PR",
    detectedAt: "2026-08-10T10:15:00Z",
    publishedAt: "2026-08-10T09:00:00Z",
  },
  {
    id: "sig-3",
    type: "HIRING_SURGE",
    company: "BetNova Group",
    companyId: "comp-1",
    jurisdiction: "Brazil",
    flag: "🇧🇷",
    title: "BetNova posts 5 backend + 2 platform architect roles",
    summary: "7 engineering positions opened in the past week. Role descriptions mention 'building core platform infrastructure' and 'greenfield casino backend' — no existing platform vendor referenced.",
    confidence: 88,
    source: "primary",
    sourceName: "LinkedIn Jobs",
    detectedAt: "2026-08-09T16:00:00Z",
  },
  {
    id: "sig-4",
    type: "NEW_LICENSE",
    company: "Circa Sports Arizona LLC",
    companyId: "comp-2",
    jurisdiction: "Arizona, USA",
    flag: "🇺🇸",
    title: "Circa Sports granted Arizona event-wagering license",
    summary: "Arizona Department of Gaming approved Circa Sports as an event-wagering operator under a tribal designee agreement with the Tohono O'odham Nation.",
    confidence: 98,
    source: "primary",
    sourceName: "Arizona DoG",
    detectedAt: "2026-08-09T10:15:00Z",
    publishedAt: "2026-08-09T08:00:00Z",
  },
  {
    id: "sig-5",
    type: "PROVIDER_CHANGE",
    company: "NovaBet",
    companyId: "comp-3",
    jurisdiction: "Malta",
    flag: "🇲🇹",
    title: "NovaBet appears to be migrating platform provider",
    summary: "Multiple job postings reference 'platform migration' and 'vendor evaluation'. Current provider (SoftSwiss) not mentioned in recent postings — suggests active transition.",
    confidence: 70,
    source: "inference",
    sourceName: "AI Analysis",
    detectedAt: "2026-08-08T16:45:00Z",
  },
  {
    id: "sig-6",
    type: "ENGINEERING_HIRING",
    company: "NovaBet",
    companyId: "comp-3",
    jurisdiction: "Malta",
    flag: "🇲🇹",
    title: "NovaBet hiring 4 platform engineers",
    summary: "4 senior platform engineering roles posted on LinkedIn and company careers page. Requirements include microservices, event-driven architecture, and iGaming platform experience.",
    confidence: 85,
    source: "primary",
    sourceName: "LinkedIn Jobs",
    detectedAt: "2026-08-08T14:30:00Z",
  },
  {
    id: "sig-7",
    type: "NEW_BRAND",
    company: "GoldStar Gaming",
    companyId: "comp-4",
    jurisdiction: "Ontario, Canada",
    flag: "🇨🇦",
    title: "GoldStar announces new Ontario casino brand",
    summary: "GoldStar Gaming announced 'GoldStar Casino' targeting the Ontario iGaming market. Press release mentions Q1 2027 launch and active vendor selection process.",
    confidence: 80,
    source: "company",
    sourceName: "Company PR",
    detectedAt: "2026-08-07T09:20:00Z",
    publishedAt: "2026-08-07T08:00:00Z",
  },
  {
    id: "sig-8",
    type: "MARKET_EXPANSION",
    company: "GoldStar Gaming",
    companyId: "comp-4",
    jurisdiction: "Ontario, Canada",
    flag: "🇨🇦",
    title: "GoldStar files for Ontario iGaming registration",
    summary: "GoldStar Gaming filed for registration with the Alcohol and Gaming Commission of Ontario (AGCO) to operate as an internet gaming operator.",
    confidence: 90,
    source: "primary",
    sourceName: "AGCO",
    detectedAt: "2026-08-07T09:00:00Z",
  },
  {
    id: "sig-9",
    type: "LICENSE_CHANGE",
    company: "Betway Group",
    companyId: "comp-5",
    jurisdiction: "UK",
    flag: "🇬🇧",
    title: "Betway UKGC license conditions modified",
    summary: "UKGC modified Betway's operating license conditions following regulatory assessment. New conditions relate to enhanced due diligence and source of funds checks.",
    confidence: 95,
    source: "primary",
    sourceName: "UKGC",
    detectedAt: "2026-08-06T11:00:00Z",
    publishedAt: "2026-08-06T10:00:00Z",
  },
  {
    id: "sig-10",
    type: "ACQUISITION",
    company: "Luckia Gaming Group",
    companyId: "comp-6",
    jurisdiction: "Spain",
    flag: "🇪🇸",
    title: "Luckia acquires LatAm operator JuegaYa",
    summary: "Luckia Gaming Group completed acquisition of JuegaYa, a Colombia-based online gaming operator, for an undisclosed sum. Deal includes JuegaYa's Colombian and Peruvian licenses.",
    confidence: 92,
    source: "secondary",
    sourceName: "iGaming Business",
    detectedAt: "2026-08-05T08:30:00Z",
    publishedAt: "2026-08-05T07:00:00Z",
  },
  {
    id: "sig-11",
    type: "NEW_CASINO",
    company: "Pinnacle Entertainment",
    companyId: "comp-7",
    jurisdiction: "Curaçao",
    flag: "🇨🇼",
    title: "Pinnacle launches crypto casino brand 'PinVault'",
    summary: "New crypto-native casino brand launched under Curaçao license. Job postings mention evaluating white-label and turnkey solutions for rapid market entry.",
    confidence: 72,
    source: "secondary",
    sourceName: "SBC News",
    detectedAt: "2026-08-04T15:10:00Z",
    publishedAt: "2026-08-04T14:00:00Z",
  },
  {
    id: "sig-12",
    type: "ENGINEERING_HIRING",
    company: "Yolo Group",
    companyId: "comp-8",
    jurisdiction: "Estonia",
    flag: "🇪🇪",
    title: "Yolo Group hiring senior platform and DevOps engineers",
    summary: "Multiple senior roles posted: Platform Architect, Senior Backend Engineer (Go), and DevOps Lead. Descriptions mention 'next-generation platform' and 'infrastructure modernization'.",
    confidence: 80,
    source: "primary",
    sourceName: "LinkedIn Jobs",
    detectedAt: "2026-08-03T12:00:00Z",
  },
  {
    id: "sig-13",
    type: "LICENSE_APPROVAL",
    company: "EveryMatrix",
    companyId: "comp-10",
    jurisdiction: "Alberta, Canada",
    flag: "🇨🇦",
    title: "EveryMatrix receives Alberta gaming supplier license",
    summary: "EveryMatrix approved as a registered gaming supplier by the Alberta Gaming, Liquor and Cannabis Commission (AGLC).",
    confidence: 95,
    source: "primary",
    sourceName: "AGLC",
    detectedAt: "2026-08-02T14:00:00Z",
  },
  {
    id: "sig-14",
    type: "NEW_PRODUCT",
    company: "Wazdan Games",
    companyId: "comp-9",
    jurisdiction: "Malta",
    flag: "🇲🇹",
    title: "Wazdan enters live dealer market with new studio",
    summary: "Wazdan announced a live dealer gaming studio in Malta, expanding beyond slots and table games into the live casino vertical.",
    confidence: 75,
    source: "secondary",
    sourceName: "Gaming Intelligence",
    detectedAt: "2026-08-02T09:45:00Z",
    publishedAt: "2026-08-02T08:00:00Z",
  },
  {
    id: "sig-15",
    type: "REGULATORY_CHANGE",
    company: "Market-wide",
    companyId: "comp-0",
    jurisdiction: "Brazil",
    flag: "🇧🇷",
    title: "Brazil publishes final iGaming technical standards",
    summary: "SECAP published final technical standards for online gaming operators in Brazil, effective January 2027. Requires certified RNG, player protection measures, and data localization.",
    confidence: 98,
    source: "primary",
    sourceName: "SECAP (Brazil)",
    detectedAt: "2026-08-01T10:00:00Z",
    publishedAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "sig-16",
    type: "SOFT_LAUNCH",
    company: "Unknown",
    companyId: "comp-0",
    jurisdiction: "Global",
    flag: "🌐",
    title: "New TLS certificate: megaspins.casino",
    summary: "CT logs reveal a new TLS certificate for megaspins.casino issued by Let's Encrypt. Domain not associated with any known operator — possible stealth launch of a new casino brand.",
    confidence: 60,
    source: "primary",
    sourceName: "crt.sh CT Logs",
    detectedAt: "2026-08-10T18:00:00Z",
  },
  {
    id: "sig-17",
    type: "SOFT_LAUNCH",
    company: "Unknown",
    companyId: "comp-0",
    jurisdiction: "Global",
    flag: "🌐",
    title: "New TLS certificate: luckystreak.bet",
    summary: "CT logs detected a new gambling-related domain luckystreak.bet with a freshly issued certificate. No WHOIS match to known operators.",
    confidence: 55,
    source: "primary",
    sourceName: "crt.sh CT Logs",
    detectedAt: "2026-08-09T22:00:00Z",
  },
  {
    id: "sig-18",
    type: "PLATFORM_PAIN",
    company: "RoyalBet Casino",
    companyId: "comp-0",
    jurisdiction: "Curaçao",
    flag: "🇨🇼",
    title: "Casino Guru Safety Index dropped for RoyalBet Casino",
    summary: "RoyalBet Casino's Safety Index on Casino Guru fell from 7.2 to 5.8. Increase in unresolved complaints about withdrawal delays and software glitches.",
    confidence: 70,
    source: "secondary",
    sourceName: "Casino Guru",
    detectedAt: "2026-08-09T06:00:00Z",
  },
  {
    id: "sig-19",
    type: "PAYMENTS_NEED",
    company: "SpinCity Online",
    companyId: "comp-0",
    jurisdiction: "Malta",
    flag: "🇲🇹",
    title: "Payment complaints spike for SpinCity Online",
    summary: "3 new payment-related complaints filed on AskGamblers in the past week for SpinCity Online, citing delayed withdrawals and declined e-wallet transactions.",
    confidence: 72,
    source: "secondary",
    sourceName: "AskGamblers",
    detectedAt: "2026-08-08T12:00:00Z",
  },
  {
    id: "sig-20",
    type: "PLATFORM_MIGRATION",
    company: "BetFlash",
    companyId: "comp-0",
    jurisdiction: "Malta",
    flag: "🇲🇹",
    title: "Technical complaints indicate platform issues at BetFlash",
    summary: "Multiple Casino Guru complaints cite frequent game loading errors and site downtime at BetFlash. Pattern consistent with platform instability — operator may be evaluating migration.",
    confidence: 65,
    source: "inference",
    sourceName: "Casino Guru",
    detectedAt: "2026-08-07T14:00:00Z",
  },
];

export const SEED_COMPANIES: SeedCompany[] = [
  {
    id: "comp-1",
    name: "BetNova Group",
    legalName: "BetNova Entretenimento Digital Ltda",
    country: "Brazil",
    flag: "🇧🇷",
    type: "operator",
    employees: 85,
    website: "betnova.com.br",
    description: "Emerging Brazilian online gaming operator focused on sports betting and casino. Recently funded and licensed under new federal framework.",
    licenses: 1,
    signals: 3,
    score: 96,
    aliases: ["BetNova", "BetNova Brasil"],
    domains: ["betnova.com.br"],
    isActive: true,
  },
  {
    id: "comp-2",
    name: "Circa Sports Arizona LLC",
    legalName: "Circa Sports Arizona LLC",
    country: "United States",
    flag: "🇺🇸",
    type: "operator",
    employees: 450,
    website: "circasports.com",
    description: "US sportsbook operator expanding from Nevada into Arizona via tribal partnership. Known for the Circa Sports app and downtown Las Vegas properties.",
    licenses: 2,
    signals: 1,
    score: 86,
    aliases: ["Circa Sports", "Circa"],
    domains: ["circasports.com", "circalasvegas.com"],
    isActive: true,
  },
  {
    id: "comp-3",
    name: "NovaBet",
    legalName: "NovaBet Ltd",
    country: "Malta",
    flag: "🇲🇹",
    type: "operator",
    employees: 220,
    website: "novabet.com",
    description: "Mid-size Malta-based operator running casino and sportsbook. Signals suggest active platform migration away from current provider.",
    licenses: 1,
    signals: 2,
    score: 82,
    aliases: ["NovaBet", "Nova Bet"],
    domains: ["novabet.com"],
    isActive: true,
  },
  {
    id: "comp-4",
    name: "GoldStar Gaming",
    country: "Canada",
    flag: "🇨🇦",
    type: "operator",
    employees: 35,
    website: "goldstargaming.ca",
    description: "Canadian startup launching a new online casino brand targeting the Ontario regulated market. In early vendor selection phase.",
    licenses: 0,
    signals: 2,
    score: 79,
    aliases: ["GoldStar", "GoldStar Casino"],
    domains: ["goldstargaming.ca"],
    isActive: true,
  },
  {
    id: "comp-5",
    name: "Betway Group",
    legalName: "Betway Limited",
    country: "United Kingdom",
    flag: "🇬🇧",
    type: "operator",
    employees: 1800,
    website: "betway.com",
    description: "Major global online gambling brand operating sportsbook and casino across multiple regulated markets. Part of Super Group.",
    licenses: 8,
    signals: 1,
    score: 74,
    aliases: ["Betway", "Betway Limited", "Super Group"],
    domains: ["betway.com", "betwaygroup.com"],
    isActive: true,
  },
  {
    id: "comp-6",
    name: "Luckia Gaming Group",
    legalName: "Luckia Gaming Group S.A.",
    country: "Spain",
    flag: "🇪🇸",
    type: "operator",
    employees: 600,
    website: "luckia.es",
    description: "Spanish gaming group operating retail and online casino/sportsbook. Recently acquired a LatAm operator to expand into Colombia and Peru.",
    licenses: 3,
    signals: 1,
    score: 71,
    aliases: ["Luckia", "Grupo Luckia"],
    domains: ["luckia.es", "luckia.com"],
    isActive: true,
  },
  {
    id: "comp-7",
    name: "Pinnacle Entertainment",
    legalName: "Pinnacle Entertainment N.V.",
    country: "Curaçao",
    flag: "🇨🇼",
    type: "operator",
    employees: 150,
    website: "pinnacle.com",
    description: "Curaçao-licensed operator known for sharp odds and low margins. Recently launched a crypto-native casino brand.",
    licenses: 1,
    signals: 1,
    score: 68,
    aliases: ["Pinnacle", "PinVault"],
    domains: ["pinnacle.com", "pinvault.io"],
    isActive: true,
  },
  {
    id: "comp-8",
    name: "Yolo Group",
    legalName: "Yolo Group OU",
    country: "Estonia",
    flag: "🇪🇪",
    type: "operator",
    employees: 900,
    website: "yolo.com",
    description: "Estonian crypto-friendly gaming group operating multiple brands including Sportsbet.io and Bitcasino. Strong engineering team, currently hiring for platform modernization.",
    licenses: 3,
    signals: 1,
    score: 65,
    aliases: ["Yolo", "Coingaming Group"],
    domains: ["yolo.com", "sportsbet.io", "bitcasino.io"],
    isActive: true,
  },
  {
    id: "comp-9",
    name: "Wazdan Games",
    legalName: "Wazdan Limited",
    country: "Malta",
    flag: "🇲🇹",
    type: "studio",
    employees: 300,
    website: "wazdan.com",
    description: "Malta-based game development studio specializing in online slots. Expanding into live dealer gaming with a new Malta-based studio.",
    licenses: 4,
    signals: 1,
    score: 58,
    aliases: ["Wazdan"],
    domains: ["wazdan.com"],
    isActive: true,
  },
  {
    id: "comp-10",
    name: "EveryMatrix",
    legalName: "EveryMatrix N.V.",
    country: "Malta",
    flag: "🇲🇹",
    type: "vendor",
    employees: 800,
    website: "everymatrix.com",
    description: "B2B iGaming platform provider offering casino, sportsbook, and payment solutions. Multi-jurisdiction licensed.",
    licenses: 6,
    signals: 1,
    score: undefined,
    aliases: ["EveryMatrix", "EM"],
    domains: ["everymatrix.com"],
    isActive: true,
  },
  {
    id: "comp-11",
    name: "Superbet Group",
    legalName: "Superbet Group Ltd",
    country: "Romania",
    flag: "🇷🇴",
    type: "operator",
    employees: 4000,
    website: "superbet.com",
    description: "Largest gaming operator in Romania with expanding presence in Poland and Belgium. Backed by Blackstone investment.",
    licenses: 4,
    signals: 0,
    score: undefined,
    aliases: ["Superbet", "Napoleon Sports"],
    domains: ["superbet.com", "superbet.ro", "napoleongames.be"],
    isActive: true,
  },
  {
    id: "comp-12",
    name: "Soft2Bet",
    legalName: "Soft2Bet Ltd",
    country: "Malta",
    flag: "🇲🇹",
    type: "operator",
    employees: 400,
    website: "soft2bet.com",
    description: "Malta-based operator and white-label provider running multiple casino and sportsbook brands across European markets.",
    licenses: 3,
    signals: 0,
    score: undefined,
    aliases: ["Soft2Bet", "S2B"],
    domains: ["soft2bet.com"],
    isActive: true,
  },
];

export const SEED_LICENSES: SeedLicense[] = [
  {
    id: "lic-1",
    company: "BetNova Group",
    companyId: "comp-1",
    licenseNumber: "BR-FED-2026-0847",
    jurisdiction: "Brazil (Federal)",
    flag: "🇧🇷",
    regulator: "SECAP",
    licenseType: "Online Gaming (Casino + Sports)",
    status: "active",
    legalEntity: "BetNova Entretenimento Digital Ltda",
    effectiveDate: "2026-08-01",
    lastChecked: "2026-08-10",
  },
  {
    id: "lic-2",
    company: "Circa Sports Arizona LLC",
    companyId: "comp-2",
    licenseNumber: "AZ-EW-2026-0112",
    jurisdiction: "Arizona, USA",
    flag: "🇺🇸",
    regulator: "Arizona DoG",
    licenseType: "Event Wagering Operator",
    status: "active",
    legalEntity: "Circa Sports Arizona LLC",
    effectiveDate: "2026-08-05",
    expiryDate: "2028-08-05",
    lastChecked: "2026-08-09",
  },
  {
    id: "lic-3",
    company: "Circa Sports Arizona LLC",
    companyId: "comp-2",
    licenseNumber: "NV-GC-2019-0891",
    jurisdiction: "Nevada, USA",
    flag: "🇺🇸",
    regulator: "Nevada Gaming Control Board",
    licenseType: "Interactive Gaming Operator",
    status: "active",
    legalEntity: "Circa Sports LLC",
    effectiveDate: "2019-10-01",
    expiryDate: "2027-10-01",
    lastChecked: "2026-07-15",
  },
  {
    id: "lic-4",
    company: "NovaBet",
    companyId: "comp-3",
    licenseNumber: "MGA/B2C/789/2021",
    jurisdiction: "Malta",
    flag: "🇲🇹",
    regulator: "MGA",
    licenseType: "B2C (Type 1 & Type 2)",
    status: "active",
    legalEntity: "NovaBet Ltd",
    effectiveDate: "2021-06-15",
    expiryDate: "2027-06-15",
    lastChecked: "2026-08-01",
  },
  {
    id: "lic-5",
    company: "Betway Group",
    companyId: "comp-5",
    licenseNumber: "000-039011-R-319417",
    jurisdiction: "UK",
    flag: "🇬🇧",
    regulator: "UKGC",
    licenseType: "Remote Casino & Betting",
    status: "active",
    legalEntity: "Betway Limited",
    effectiveDate: "2015-03-01",
    lastChecked: "2026-08-06",
  },
  {
    id: "lic-6",
    company: "Betway Group",
    companyId: "comp-5",
    licenseNumber: "MGA/B2C/130/2006",
    jurisdiction: "Malta",
    flag: "🇲🇹",
    regulator: "MGA",
    licenseType: "B2C (Type 1, 2 & 3)",
    status: "active",
    legalEntity: "Betway Limited",
    effectiveDate: "2006-09-01",
    expiryDate: "2027-09-01",
    lastChecked: "2026-07-20",
  },
  {
    id: "lic-7",
    company: "Luckia Gaming Group",
    companyId: "comp-6",
    licenseNumber: "DGOJ-2014-0089",
    jurisdiction: "Spain",
    flag: "🇪🇸",
    regulator: "DGOJ",
    licenseType: "Online Gaming General",
    status: "active",
    legalEntity: "Luckia Games S.A.",
    effectiveDate: "2014-07-01",
    lastChecked: "2026-07-25",
  },
  {
    id: "lic-8",
    company: "Luckia Gaming Group",
    companyId: "comp-6",
    licenseNumber: "COL-COLJUEGOS-2026-2201",
    jurisdiction: "Colombia",
    flag: "🇨🇴",
    regulator: "Coljuegos",
    licenseType: "Online Gaming Operator",
    status: "pending",
    legalEntity: "JuegaYa S.A.S.",
    effectiveDate: "2026-07-01",
    lastChecked: "2026-08-05",
  },
  {
    id: "lic-9",
    company: "Pinnacle Entertainment",
    companyId: "comp-7",
    licenseNumber: "CUR-8048-JAZ-2018",
    jurisdiction: "Curaçao",
    flag: "🇨🇼",
    regulator: "GCB Curaçao",
    licenseType: "Master Gaming License",
    status: "active",
    legalEntity: "Pinnacle Entertainment N.V.",
    effectiveDate: "2018-01-01",
    lastChecked: "2026-07-10",
  },
  {
    id: "lic-10",
    company: "EveryMatrix",
    companyId: "comp-10",
    licenseNumber: "AGLC-SUP-2026-0341",
    jurisdiction: "Alberta, Canada",
    flag: "🇨🇦",
    regulator: "AGLC",
    licenseType: "Gaming Supplier",
    status: "active",
    legalEntity: "EveryMatrix N.V.",
    effectiveDate: "2026-08-01",
    lastChecked: "2026-08-02",
  },
  {
    id: "lic-11",
    company: "Yolo Group",
    companyId: "comp-8",
    licenseNumber: "EE-HKS000066",
    jurisdiction: "Estonia",
    flag: "🇪🇪",
    regulator: "EMTA",
    licenseType: "Online Gambling Operator",
    status: "active",
    legalEntity: "Yolo Group OU",
    effectiveDate: "2020-03-15",
    lastChecked: "2026-07-01",
  },
  {
    id: "lic-12",
    company: "Wazdan Games",
    companyId: "comp-9",
    licenseNumber: "MGA/B2B/543/2018",
    jurisdiction: "Malta",
    flag: "🇲🇹",
    regulator: "MGA",
    licenseType: "B2B (Type 1 & Type 2)",
    status: "active",
    legalEntity: "Wazdan Limited",
    effectiveDate: "2018-11-01",
    expiryDate: "2028-11-01",
    lastChecked: "2026-07-15",
  },
];

export const SEED_NEWS: SeedNewsArticle[] = [
  {
    id: "news-1",
    title: "Brazil publishes final technical standards for online gaming operators",
    publisher: "iGaming Business",
    publishedAt: "2026-08-10T08:00:00Z",
    excerpt: "SECAP has released the final version of its technical standards for online gaming, covering RNG certification, player protection, data localization, and responsible gambling requirements for operators launching under the new federal framework.",
    url: "https://igamingbusiness.com/brazil-technical-standards",
    topics: ["Regulation", "Brazil", "Compliance"],
    entities: ["SECAP", "Brazil"],
    signalTypes: ["REGULATORY_CHANGE"],
  },
  {
    id: "news-2",
    title: "BetNova raises €8M to fuel Brazilian market expansion",
    publisher: "Gaming Intelligence",
    publishedAt: "2026-08-10T09:00:00Z",
    excerpt: "Brazilian gaming startup BetNova Group has closed an €8M Series A round led by Acme Ventures, with participation from iGaming Capital Partners. The company plans to use the funds to build out its technology platform and launch operations under the new federal license.",
    url: "https://gamingintelligence.com/betnova-8m-series-a",
    topics: ["Funding", "Brazil", "Startups"],
    entities: ["BetNova Group", "Acme Ventures"],
    signalTypes: ["FUNDING"],
  },
  {
    id: "news-3",
    title: "Circa Sports expands to Arizona with tribal partnership",
    publisher: "SBC News",
    publishedAt: "2026-08-09T07:00:00Z",
    excerpt: "Circa Sports has received an event-wagering license in Arizona through a designee agreement with the Tohono O'odham Nation, marking the Las Vegas-based operator's first expansion beyond Nevada.",
    url: "https://sbcnews.co.uk/circa-sports-arizona",
    topics: ["US Market", "Licensing", "Tribal Gaming"],
    entities: ["Circa Sports", "Tohono O'odham Nation"],
    signalTypes: ["NEW_LICENSE", "MARKET_EXPANSION"],
  },
  {
    id: "news-4",
    title: "Luckia completes acquisition of Colombian operator JuegaYa",
    publisher: "iGaming Business",
    publishedAt: "2026-08-05T07:00:00Z",
    excerpt: "Spanish gaming group Luckia has completed its acquisition of JuegaYa, a Colombia-based online gaming operator with licenses in Colombia and Peru. The deal strengthens Luckia's presence in the fast-growing Latin American regulated market.",
    url: "https://igamingbusiness.com/luckia-juegaya-acquisition",
    topics: ["M&A", "LatAm", "Spain"],
    entities: ["Luckia Gaming Group", "JuegaYa"],
    signalTypes: ["ACQUISITION"],
  },
  {
    id: "news-5",
    title: "Pinnacle launches crypto-native casino brand PinVault",
    publisher: "SBC News",
    publishedAt: "2026-08-04T14:00:00Z",
    excerpt: "Pinnacle Entertainment has launched PinVault, a new crypto-friendly online casino operating under its existing Curaçao license. The brand targets cryptocurrency enthusiasts with provably fair games and instant crypto payouts.",
    url: "https://sbcnews.co.uk/pinnacle-pinvault-launch",
    topics: ["Crypto", "Casino Launch", "Curaçao"],
    entities: ["Pinnacle Entertainment", "PinVault"],
    signalTypes: ["NEW_CASINO"],
  },
  {
    id: "news-6",
    title: "UKGC modifies Betway operating license conditions",
    publisher: "Gaming Intelligence",
    publishedAt: "2026-08-06T10:00:00Z",
    excerpt: "The UK Gambling Commission has modified the operating license conditions for Betway Limited following a regulatory assessment. The new conditions impose enhanced requirements for customer due diligence and source of funds verification.",
    url: "https://gamingintelligence.com/ukgc-betway-conditions",
    topics: ["Regulation", "UK", "Compliance"],
    entities: ["Betway", "UKGC"],
    signalTypes: ["LICENSE_CHANGE"],
  },
  {
    id: "news-7",
    title: "Wazdan enters live dealer market with Malta studio",
    publisher: "Gaming Intelligence",
    publishedAt: "2026-08-02T08:00:00Z",
    excerpt: "Slot specialist Wazdan has announced plans to expand into live dealer gaming, with a new dedicated studio in Malta. The move represents a significant strategic pivot for the game developer.",
    url: "https://gamingintelligence.com/wazdan-live-dealer",
    topics: ["Live Casino", "Game Development", "Malta"],
    entities: ["Wazdan"],
    signalTypes: ["NEW_PRODUCT"],
  },
  {
    id: "news-8",
    title: "EveryMatrix receives Alberta gaming supplier approval",
    publisher: "iGaming Business",
    publishedAt: "2026-08-02T11:00:00Z",
    excerpt: "B2B platform provider EveryMatrix has been approved as a registered gaming supplier in Alberta, Canada, further expanding its North American regulatory footprint.",
    url: "https://igamingbusiness.com/everymatrix-alberta",
    topics: ["Licensing", "Canada", "B2B"],
    entities: ["EveryMatrix", "AGLC"],
    signalTypes: ["LICENSE_APPROVAL"],
  },
  {
    id: "news-9",
    title: "GoldStar Gaming targets Ontario with new casino brand",
    publisher: "SBC News",
    publishedAt: "2026-08-07T08:00:00Z",
    excerpt: "Canadian startup GoldStar Gaming has announced plans to launch a new online casino brand in the Ontario regulated market, with an expected Q1 2027 go-live date.",
    url: "https://sbcnews.co.uk/goldstar-ontario",
    topics: ["Ontario", "Casino Launch", "Canada"],
    entities: ["GoldStar Gaming"],
    signalTypes: ["NEW_BRAND", "MARKET_EXPANSION"],
  },
  {
    id: "news-10",
    title: "Yolo Group hiring spree signals platform overhaul",
    publisher: "iGaming Business",
    publishedAt: "2026-08-03T09:00:00Z",
    excerpt: "Crypto-forward gaming group Yolo is on a hiring blitz for senior platform and infrastructure engineers, fueling speculation about a major technology refresh across its portfolio of brands.",
    url: "https://igamingbusiness.com/yolo-hiring",
    topics: ["Hiring", "Technology", "Crypto"],
    entities: ["Yolo Group"],
    signalTypes: ["ENGINEERING_HIRING"],
  },
];

export const SEED_CONTACTS: SeedContact[] = [
  {
    id: "con-1",
    name: "Rafael Mendes",
    title: "CTO",
    company: "BetNova Group",
    companyId: "comp-1",
    email: "r.mendes@betnova.com.br",
    linkedin: "linkedin.com/in/rafaelmendes",
    isDecisionMaker: true,
    confidence: 85,
  },
  {
    id: "con-2",
    name: "Ana Costa",
    title: "VP Engineering",
    company: "BetNova Group",
    companyId: "comp-1",
    linkedin: "linkedin.com/in/anacosta",
    isDecisionMaker: true,
    confidence: 72,
  },
  {
    id: "con-3",
    name: "Derek Stevens",
    title: "CEO",
    company: "Circa Sports Arizona LLC",
    companyId: "comp-2",
    isDecisionMaker: true,
    confidence: 95,
  },
  {
    id: "con-4",
    name: "Maria Petrova",
    title: "Head of Platform",
    company: "NovaBet",
    companyId: "comp-3",
    linkedin: "linkedin.com/in/mariapetrova",
    isDecisionMaker: true,
    confidence: 68,
  },
  {
    id: "con-5",
    name: "James Wong",
    title: "CTO",
    company: "GoldStar Gaming",
    companyId: "comp-4",
    email: "james@goldstargaming.ca",
    linkedin: "linkedin.com/in/jameswong",
    isDecisionMaker: true,
    confidence: 78,
  },
  {
    id: "con-6",
    name: "Elena García",
    title: "Director of Digital",
    company: "Luckia Gaming Group",
    companyId: "comp-6",
    linkedin: "linkedin.com/in/elenagarcia",
    isDecisionMaker: true,
    confidence: 65,
  },
  {
    id: "con-7",
    name: "Viktor Kask",
    title: "VP Engineering",
    company: "Yolo Group",
    companyId: "comp-8",
    linkedin: "linkedin.com/in/viktorkask",
    isDecisionMaker: true,
    confidence: 70,
  },
];

export const SEED_SOURCES = [
  { name: "UKGC", type: "Regulator", status: "active" as const, records: 2665, lastCrawl: "2026-08-10T06:00:00Z", frequency: "24h", jurisdiction: "United Kingdom", reliability: 5, connector: "ukgc" },
  { name: "GCGRA (UAE)", type: "Regulator", status: "active" as const, records: 26, lastCrawl: "2026-08-10T06:00:00Z", frequency: "24h", jurisdiction: "UAE", reliability: 4, connector: "gcgra" },
  { name: "iGaming Business", type: "News", status: "active" as const, records: 847, lastCrawl: "2026-08-10T08:00:00Z", frequency: "6h", jurisdiction: "Global", reliability: 4, connector: "igb" },
  { name: "Gaming Intelligence", type: "News", status: "active" as const, records: 623, lastCrawl: "2026-08-10T08:00:00Z", frequency: "6h", jurisdiction: "Global", reliability: 4, connector: "gaming_intelligence" },
  { name: "SBC News", type: "News", status: "active" as const, records: 512, lastCrawl: "2026-08-10T08:00:00Z", frequency: "6h", jurisdiction: "Global", reliability: 4, connector: "sbc" },
  { name: "crt.sh CT Logs", type: "Search", status: "active" as const, records: 312, lastCrawl: "2026-08-10T12:00:00Z", frequency: "12h", jurisdiction: "Global", reliability: 5, connector: "crtsh" },
  { name: "Casino Guru", type: "Complaint", status: "active" as const, records: 1840, lastCrawl: "2026-08-10T06:00:00Z", frequency: "24h", jurisdiction: "Global", reliability: 4, connector: "casino_guru" },
  { name: "AskGamblers", type: "Complaint", status: "active" as const, records: 1265, lastCrawl: "2026-08-10T06:00:00Z", frequency: "24h", jurisdiction: "Global", reliability: 4, connector: "askgamblers" },
  { name: "Arizona DoG", type: "Regulator", status: "planned" as const, records: 0, lastCrawl: null, frequency: "24h", jurisdiction: "Arizona, USA", reliability: 5, connector: null },
  { name: "AGLC (Alberta)", type: "Regulator", status: "planned" as const, records: 0, lastCrawl: null, frequency: "24h", jurisdiction: "Alberta, Canada", reliability: 5, connector: null },
  { name: "MGA (Malta)", type: "Regulator", status: "planned" as const, records: 0, lastCrawl: null, frequency: "48h", jurisdiction: "Malta", reliability: 5, connector: null },
  { name: "DGOJ (Spain)", type: "Regulator", status: "planned" as const, records: 0, lastCrawl: null, frequency: "48h", jurisdiction: "Spain", reliability: 5, connector: null },
  { name: "LinkedIn Jobs", type: "Jobs", status: "planned" as const, records: 0, lastCrawl: null, frequency: "12h", jurisdiction: "Global", reliability: 3, connector: null },
  { name: "Crunchbase", type: "Funding", status: "planned" as const, records: 0, lastCrawl: null, frequency: "24h", jurisdiction: "Global", reliability: 4, connector: null },
];

export function formatTimeAgo(dateStr: string): string {
  const now = new Date("2026-08-11T12:00:00Z");
  const date = new Date(dateStr);
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 60) return `${diffMins}m ago`;
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays === 1) return "1d ago";
  return `${diffDays}d ago`;
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}
